import { Box, Button, Text, TextField, Image } from "@skynexui/components";
import appConfig from "../config.json";

import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
	const username = "vini54";
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<>
				<Box className={styles.background}>
					<Box
						styleSheet={{
							display: "flex",
							alignItems: "center",
							justifyContent: "space-between",
							flexDirection: {
								xs: "column",
								sm: "row",
							},
							width: "100%",
							maxWidth: "700px",
							borderRadius: "5px",
							padding: "32px",
							margin: "16px",
							boxShadow: "0 2px 10px 0 rgb(0 0 0 / 20%)",
							backgroundColor: appConfig.theme.colors.neutrals[700],
						}}
					>
						{/* Formulário */}
						<Box
							as="form"
              className={styles.form}
							styleSheet={{
								width: { xs: "100%", sm: "50%" },
							}}
						>
							<Titulo tag="h2">Boas vindas de volta!</Titulo>
							<Text
								variant="body3"
								styleSheet={{
									marginBottom: "32px",
									color: appConfig.theme.colors.neutrals[300],
								}}
							>
								{appConfig.name}
							</Text>

							<TextField
								fullWidth
								textFieldColors={{
									neutral: {
										textColor: appConfig.theme.colors.neutrals[200],
										mainColor: appConfig.theme.colors.neutrals[900],
										mainColorHighlight: appConfig.theme.colors.primary[500],
										backgroundColor: appConfig.theme.colors.neutrals[800],
									},
								}}
							/>
							<Button
								type="submit"
								label="Entrar"
								fullWidth
								buttonColors={{
									contrastColor: appConfig.theme.colors.neutrals["000"],
									mainColor: appConfig.theme.colors.primary[500],
									mainColorLight: appConfig.theme.colors.primary[400],
									mainColorStrong: appConfig.theme.colors.primary[600],
								}}
							/>
						</Box>
						{/* Formulário */}

						{/* Photo Area */}
						<Box
							styleSheet={{
								display: "flex",
								flexDirection: "column",
								alignItems: "center",
								maxWidth: "200px",
								padding: "16px",
								backgroundColor: appConfig.theme.colors.neutrals[800],
								border: "1px solid",
								borderColor: appConfig.theme.colors.neutrals[999],
								borderRadius: "10px",
								flex: 1,
								minHeight: "240px",
							}}
						>
							<Image
								styleSheet={{
									borderRadius: "50%",
									marginBottom: "16px",
								}}
								src={`https://github.com/${username}.png`}
							/>
							<Text
								variant="body4"
								styleSheet={{
									color: appConfig.theme.colors.neutrals[200],
									backgroundColor: appConfig.theme.colors.neutrals[900],
									padding: "3px 10px",
									borderRadius: "1000px",
								}}
							>
								{username}
							</Text>
						</Box>
						{/* Photo Area */}
					</Box>
				</Box>
			</>
		</div>
	);
}

function Titulo(props) {
	const Tag = props.tag || "h1";
	return (
		<>
			<Tag>{props.children}</Tag>
			<style jsx>{`
				${Tag} {
					color: ${appConfig.theme.colors.neutrals["000"]};
					font-size: 24px;
					font-weight: 600;
				}
			`}</style>
		</>
	);
}
